### ISSUE TITLE
documentation of sim-fish

### ISSUE THREAD

**Issue by zwdiscover** [fish-quant/sim-fish#3]
The link to the online documentation of sim-fish doesn't work.

**Comment by Henley13** [comment]
Hi @zwdiscover,

Yes I am rebuilding it. By next week it should be good. Where do you find the dead link by the way? In the `develop` branch?

Arthur

**Comment by zwdiscover** [comment]
The dead link was in the readme.md file. But it is missing now. Maybe you just deleted it?

**Comment by zwdiscover** [comment]
Yes, in the develop branch:  https://github.com/fish-quant/sim-fish/blob/develop/README.md
